# Generated by Django 3.1.3 on 2020-11-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Response",
            new_name="UsersAnswer",
        ),
        migrations.RenameField(
            model_name="quiztaker",
            old_name="correct_answers",
            new_name="score",
        ),
        migrations.AddField(
            model_name="quiz",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
